company_questions = {
    "General": [
        "Tell me about yourself.",
        "What do you know about our company?",
        "What do you know about our products?",
        "What do you know about our services?",
        "What are our company's core values?",
        "Who are our competitors?",
        "Why should we hire you?",
        "What makes you different from other candidates?",
        "What skills make you suitable for this company?",
        "How will you contribute to our organization?",
        "Why did you apply for this position?",
        "What do you know about our recent achievements?",
        "How do you stay updated about our company?",
        "What attracts you to our company culture?",
        "What is your understanding of this role?",
        "Why are you interested in this industry?",
        "How do your career goals align with our company?",
        "Why are you leaving your current company?",
        "What do you expect from our company?",
        "How do you handle work pressure?",
        "How do you work in a team?",
        "Describe a challenging project you completed.",
        "Describe your greatest professional achievement.",
        "Describe a difficult problem you solved.",
        "How do you manage tight deadlines?",
        "Describe a time you showed leadership.",
        "How do you prioritize multiple tasks?",
        "Describe a time you handled conflict at work.",
        "How do you respond to constructive criticism?",
        "What motivates you to perform well?",
        "What are your strengths?",
        "What are your weaknesses?",
        "Where do you see yourself in five years?",
        "Where do you see yourself in ten years?",
        "Are you willing to relocate?",
        "Are you willing to travel for work?",
        "What are your salary expectations?",
        "How soon can you join?",
        "What programming languages do you know?",
        "What frameworks have you worked with?",
        "What databases have you used?",
        "What version control systems do you use?",
        "What IDE do you prefer?",
        "What is your favorite project?",
        "What was your role in your last project?",
        "Explain your final year project.",
        "How do you debug software issues?",
        "What is your software development process?",
        "How do you ensure code quality?",
        "Have you worked in Agile?",
        "What is your experience with REST APIs?",
        "What is your experience with SQL?",
        "What is your experience with NoSQL databases?",
        "How do you optimize application performance?",
        "Describe a production issue you fixed.",
        "How do you test your applications?",
        "What testing tools have you used?",
        "What is CI/CD?",
        "What security practices do you follow?",
        "How do you protect sensitive user data?",
        "What would you do if production goes down?",
        "How do you handle customer complaints?",
        "How do you deal with difficult coworkers?",
        "Describe a situation where you failed.",
        "What did you learn from your biggest mistake?",
        "Describe a time you exceeded expectations.",
        "Describe a time you took initiative.",
        "What is your leadership style?",
        "How do you adapt to organizational change?",
        "What makes you a good cultural fit?",
        "Why do you think you'll succeed here?",
        "What do you expect during your first 90 days?",
        "How would your previous manager describe you?",
        "What questions do you have for us?",
        "How do you stay motivated at work?",
        "What would you do if you disagreed with your manager?",
        "How do you handle changing priorities?",
        "What would you do if you made a mistake in production?",
        "Describe a time you worked under pressure.",
        "How do you ensure customer satisfaction?",
        "What is your approach to problem-solving?",
        "Describe your ideal work environment.",
        "What role do you usually play in a team?",
        "How do you manage time effectively?",
        "What do you expect from your manager?",
        "What kind of company culture do you prefer?",
        "What would you do if you missed a project deadline?",
        "How do you learn new technologies quickly?",
        "How do you deal with uncertainty at work?",
        "What is your biggest professional challenge?",
        "Describe a time you handled multiple projects.",
        "What would you do if you received negative feedback?",
        "How do you handle repetitive tasks?",
        "What is your greatest accomplishment?",
        "What achievement are you most proud of?",
        "What are your long-term career aspirations?",
        "How do you define success?",
        "What motivates you beyond salary?",
        "How do you maintain work-life balance?",
        "What qualities make a great employee?",
        "What qualities make a great leader?",
        "Describe a situation where you improved a process.",
        "Describe a time you solved a customer issue.",
        "Tell us about a time you made an important decision.",
        "What would you do if your teammate wasn't contributing?",
        "How do you handle conflicts in a team?",
        "What would you do if you disagreed with company policy?",
        "What are your expectations from this job?",
        "Why do you think you are a good cultural fit?",
        "What do you know about our mission?",
        "What do you know about our vision?",
        "What recent company news caught your attention?",
        "What products or services interest you the most?",
        "What improvements would you suggest for our company?",
        "What do you think makes our company successful?",
        "How would you represent our company to customers?",
        "What would you do in your first month here?",
        "What skills are you currently improving?",
        "How do you keep yourself technically updated?",
        "What certifications have you completed?",
        "What online learning platforms do you use?",
        "What books have influenced your career?",
        "Who inspires you professionally?",
        "What do you expect from your teammates?",
        "What makes you excited about this opportunity?",
        "What would you do if assigned an unfamiliar task?",
        "How do you manage project risks?",
        "Describe your communication style.",
        "How do you build trust within a team?",
        "What would you do if a client changed requirements at the last minute?",
        "How do you ensure project quality?",
        "What is your approach to continuous improvement?",
        "How do you stay productive while working remotely?",
        "What productivity tools do you use?",
        "What collaboration tools have you used?",
        "Have you worked with Slack or Microsoft Teams?",
        "How do you document your work?",
        "What would you do if your project failed?",
        "How do you recover from setbacks?",
        "How do you maintain a positive attitude?",
        "What are your strongest soft skills?",
        "What soft skills are you improving?",
        "Describe your decision-making process.",
        "What would you do if you had limited resources?",
        "How do you handle confidential information?",
        "What would you do if you found a security issue?",
        "How do you ensure ethical behavior at work?",
        "What do you value most in an employer?",
        "What type of projects interest you the most?",
        "What impact do you want to make in our company?",
        "What would your teammates say about you?",
        "What would your manager say is your greatest strength?",
        "Why do you believe you are the best candidate?",
        "What would you do if you were selected today?",
        "What is your notice period?",
        "Are you interviewing with other companies?",
        "What are your expectations for career growth here?",
        "How do you measure your own performance?",
        "What would you do if given additional responsibilities?",
        "How do you encourage teamwork?",
        "What role does innovation play in your work?",
        "How do you approach difficult conversations?",
        "What are your expectations from company training?",
        "How do you handle fast-changing technologies?",
        "What would you do if you didn't know the answer to a question?",
        "How do you handle constructive feedback?",
        "What would you do to exceed our expectations?",
        "What excites you most about joining our organization?",
        "How would you contribute to our company's success?",
        "What unique value can you bring to our team?",
        "Why should we choose you over other candidates?",
        "What would you like to accomplish in your first year here?",
        "How do you plan to grow within our organization?",
        "What questions would you like to ask the hiring manager?"
    ],
    "Google": [
        "Tell me about yourself.",
        "Why do you want to join Google?",
        "What is your favorite Google product and how would you improve it?",
        "Describe a time you solved a complex technical problem.",
        "How do you align with Google's core values?",
        "How would you design a scalable web application?",
        "Explain MapReduce in simple terms.",
        "Where do you see yourself in five years?",
        "How does Google's business model differ from its competitors?",
        "Describe a time you used a product by Google and found a bug.",
        "Why do you think Google is a market leader?",
        "What is the biggest challenge Google is facing today?",
        "If you were the CEO of Google, what would you change?",
        "How would you improve Google's core product?",
        "What excites you most about Google's future roadmap?",
        "How do your personal values align with Google's mission?",
        "Tell me about a time you had to adapt quickly, a skill highly valued at Google.",
        "Describe a system you designed that could scale to Google's level.",
        "What is your favorite feature of Google's flagship product?",
        "How would you design a new feature for Google?",
        "What do you know about Google's recent acquisitions?",
        "How would you handle a production incident affecting millions of Google's users?",
        "Tell me about a time you had to innovate, something Google is known for.",
        "What makes Google's company culture unique in your opinion?",
        "How do you stay updated with Google's technological advancements?",
        "If hired at Google, what would you aim to achieve in your first 90 days?",
        "How would you optimize an algorithm to run efficiently on Google's infrastructure?",
        "Describe a time you demonstrated leadership principles valued at Google.",
        "What is a recent news article you read about Google, and what are your thoughts on it?",
        "How would you pitch Google's services to a potential enterprise client?",
        "What do you think is Google's biggest missed opportunity?",
        "If you could work on any team at Google, which one would it be and why?",
        "How do you prioritize tasks when working on high-impact projects at Google?",
        "What is your understanding of Google's target demographic?",
        "How would you resolve a conflict with a colleague in a fast-paced environment like Google?",
        "Tell me about a time you made a data-driven decision, a key practice at Google.",
        "How would you ensure accessibility in products developed by Google?",
        "What do you think of Google's approach to open-source software?",
        "How would you reduce latency in Google's primary application?",
        "Describe a time you received constructive feedback and how you applied it, as expected at Google.",
        "What do you think is the next big industry trend Google should focus on?",
        "How would you handle working with a globally distributed team at Google?",
        "Tell me about a time you had to manage stakeholders with conflicting interests, common at Google.",
        "What is your approach to testing and QA for large-scale systems like Google's?",
        "How would you design a caching strategy for Google's high-traffic web pages?",
        "What do you think about Google's approach to user privacy and data security?",
        "If a major competitor of Google launched a disruptive product, how would you respond?",
        "Tell me about a time you took a calculated risk, similar to how Google operates.",
        "How would you mentor a junior engineer joining your team at Google?",
        "What is your strategy for learning a new proprietary technology used at Google?",
        "How would you explain a complex technical concept to a non-technical manager at Google?",
        "What do you think about Google's impact on the global economy?"
    ],
    "Amazon": [
        "Tell me about yourself.",
        "Why do you want to join Amazon?",
        "Which of Amazon's leadership principles resonates with you the most?",
        "Describe a time you insisted on the highest standards.",
        "How do you handle customer complaints or dissatisfaction?",
        "Tell me about a time you had to deliver results under pressure.",
        "Have you worked with AWS services?",
        "How does Amazon's business model differ from its competitors?",
        "Describe a time you used a product by Amazon and found a bug.",
        "Why do you think Amazon is a market leader?",
        "What is the biggest challenge Amazon is facing today?",
        "If you were the CEO of Amazon, what would you change?",
        "How would you improve Amazon's core product?",
        "What excites you most about Amazon's future roadmap?",
        "How do your personal values align with Amazon's mission?",
        "Tell me about a time you had to adapt quickly, a skill highly valued at Amazon.",
        "Describe a system you designed that could scale to Amazon's level.",
        "What is your favorite feature of Amazon's flagship product?",
        "How would you design a new feature for Amazon?",
        "What do you know about Amazon's recent acquisitions?",
        "How would you handle a production incident affecting millions of Amazon's users?",
        "Tell me about a time you had to innovate, something Amazon is known for.",
        "What makes Amazon's company culture unique in your opinion?",
        "How do you stay updated with Amazon's technological advancements?",
        "If hired at Amazon, what would you aim to achieve in your first 90 days?",
        "How would you optimize an algorithm to run efficiently on Amazon's infrastructure?",
        "Describe a time you demonstrated leadership principles valued at Amazon.",
        "What is a recent news article you read about Amazon, and what are your thoughts on it?",
        "How would you pitch Amazon's services to a potential enterprise client?",
        "What do you think is Amazon's biggest missed opportunity?",
        "If you could work on any team at Amazon, which one would it be and why?",
        "How do you prioritize tasks when working on high-impact projects at Amazon?",
        "What is your understanding of Amazon's target demographic?",
        "How would you resolve a conflict with a colleague in a fast-paced environment like Amazon?",
        "Tell me about a time you made a data-driven decision, a key practice at Amazon.",
        "How would you ensure accessibility in products developed by Amazon?",
        "What do you think of Amazon's approach to open-source software?",
        "How would you reduce latency in Amazon's primary application?",
        "Describe a time you received constructive feedback and how you applied it, as expected at Amazon.",
        "What do you think is the next big industry trend Amazon should focus on?",
        "How would you handle working with a globally distributed team at Amazon?",
        "Tell me about a time you had to manage stakeholders with conflicting interests, common at Amazon.",
        "What is your approach to testing and QA for large-scale systems like Amazon's?",
        "How would you design a caching strategy for Amazon's high-traffic web pages?",
        "What do you think about Amazon's approach to user privacy and data security?",
        "If a major competitor of Amazon launched a disruptive product, how would you respond?",
        "Tell me about a time you took a calculated risk, similar to how Amazon operates.",
        "How would you mentor a junior engineer joining your team at Amazon?",
        "What is your strategy for learning a new proprietary technology used at Amazon?",
        "How would you explain a complex technical concept to a non-technical manager at Amazon?",
        "What do you think about Amazon's impact on the global economy?",
        "How would you troubleshoot a memory leak in a core Amazon application?",
        "Tell me about a time you exceeded expectations on a project, something Amazon expects."
    ],
    "Microsoft": [
        "Tell me about yourself.",
        "Why do you want to join Microsoft?",
        "How do you stay updated with the latest Microsoft technologies?",
        "Tell me about a time you collaborated across different teams.",
        "How do you approach building accessible software?",
        "What excites you about Microsoft's shift to cloud computing?",
        "How does Microsoft's business model differ from its competitors?",
        "Describe a time you used a product by Microsoft and found a bug.",
        "Why do you think Microsoft is a market leader?",
        "What is the biggest challenge Microsoft is facing today?",
        "If you were the CEO of Microsoft, what would you change?",
        "How would you improve Microsoft's core product?",
        "What excites you most about Microsoft's future roadmap?",
        "How do your personal values align with Microsoft's mission?",
        "Tell me about a time you had to adapt quickly, a skill highly valued at Microsoft.",
        "Describe a system you designed that could scale to Microsoft's level.",
        "What is your favorite feature of Microsoft's flagship product?",
        "How would you design a new feature for Microsoft?",
        "What do you know about Microsoft's recent acquisitions?",
        "How would you handle a production incident affecting millions of Microsoft's users?",
        "Tell me about a time you had to innovate, something Microsoft is known for.",
        "What makes Microsoft's company culture unique in your opinion?",
        "How do you stay updated with Microsoft's technological advancements?",
        "If hired at Microsoft, what would you aim to achieve in your first 90 days?",
        "How would you optimize an algorithm to run efficiently on Microsoft's infrastructure?",
        "Describe a time you demonstrated leadership principles valued at Microsoft.",
        "What is a recent news article you read about Microsoft, and what are your thoughts on it?",
        "How would you pitch Microsoft's services to a potential enterprise client?",
        "What do you think is Microsoft's biggest missed opportunity?",
        "If you could work on any team at Microsoft, which one would it be and why?",
        "How do you prioritize tasks when working on high-impact projects at Microsoft?",
        "What is your understanding of Microsoft's target demographic?",
        "How would you resolve a conflict with a colleague in a fast-paced environment like Microsoft?",
        "Tell me about a time you made a data-driven decision, a key practice at Microsoft.",
        "How would you ensure accessibility in products developed by Microsoft?",
        "What do you think of Microsoft's approach to open-source software?",
        "How would you reduce latency in Microsoft's primary application?",
        "Describe a time you received constructive feedback and how you applied it, as expected at Microsoft.",
        "What do you think is the next big industry trend Microsoft should focus on?",
        "How would you handle working with a globally distributed team at Microsoft?",
        "Tell me about a time you had to manage stakeholders with conflicting interests, common at Microsoft.",
        "What is your approach to testing and QA for large-scale systems like Microsoft's?",
        "How would you design a caching strategy for Microsoft's high-traffic web pages?",
        "What do you think about Microsoft's approach to user privacy and data security?",
        "If a major competitor of Microsoft launched a disruptive product, how would you respond?",
        "Tell me about a time you took a calculated risk, similar to how Microsoft operates.",
        "How would you mentor a junior engineer joining your team at Microsoft?",
        "What is your strategy for learning a new proprietary technology used at Microsoft?",
        "How would you explain a complex technical concept to a non-technical manager at Microsoft?",
        "What do you think about Microsoft's impact on the global economy?",
        "How would you troubleshoot a memory leak in a core Microsoft application?",
        "Tell me about a time you exceeded expectations on a project, something Microsoft expects.",
        "How would you ensure your code is maintainable for future engineers at Microsoft?"
    ],
    "Apple": [
        "Tell me about yourself.",
        "Why do you want to join Apple?",
        "How do you balance design aesthetics with engineering constraints?",
        "Describe a time when you paid extreme attention to detail.",
        "What do you think makes Apple products unique?",
        "How does Apple's business model differ from its competitors?",
        "Describe a time you used a product by Apple and found a bug.",
        "Why do you think Apple is a market leader?",
        "What is the biggest challenge Apple is facing today?",
        "If you were the CEO of Apple, what would you change?",
        "How would you improve Apple's core product?",
        "What excites you most about Apple's future roadmap?",
        "How do your personal values align with Apple's mission?",
        "Tell me about a time you had to adapt quickly, a skill highly valued at Apple.",
        "Describe a system you designed that could scale to Apple's level.",
        "What is your favorite feature of Apple's flagship product?",
        "How would you design a new feature for Apple?",
        "What do you know about Apple's recent acquisitions?",
        "How would you handle a production incident affecting millions of Apple's users?",
        "Tell me about a time you had to innovate, something Apple is known for.",
        "What makes Apple's company culture unique in your opinion?",
        "How do you stay updated with Apple's technological advancements?",
        "If hired at Apple, what would you aim to achieve in your first 90 days?",
        "How would you optimize an algorithm to run efficiently on Apple's infrastructure?",
        "Describe a time you demonstrated leadership principles valued at Apple.",
        "What is a recent news article you read about Apple, and what are your thoughts on it?",
        "How would you pitch Apple's services to a potential enterprise client?",
        "What do you think is Apple's biggest missed opportunity?",
        "If you could work on any team at Apple, which one would it be and why?",
        "How do you prioritize tasks when working on high-impact projects at Apple?",
        "What is your understanding of Apple's target demographic?",
        "How would you resolve a conflict with a colleague in a fast-paced environment like Apple?",
        "Tell me about a time you made a data-driven decision, a key practice at Apple.",
        "How would you ensure accessibility in products developed by Apple?",
        "What do you think of Apple's approach to open-source software?",
        "How would you reduce latency in Apple's primary application?",
        "Describe a time you received constructive feedback and how you applied it, as expected at Apple.",
        "What do you think is the next big industry trend Apple should focus on?",
        "How would you handle working with a globally distributed team at Apple?",
        "Tell me about a time you had to manage stakeholders with conflicting interests, common at Apple.",
        "What is your approach to testing and QA for large-scale systems like Apple's?",
        "How would you design a caching strategy for Apple's high-traffic web pages?",
        "What do you think about Apple's approach to user privacy and data security?",
        "If a major competitor of Apple launched a disruptive product, how would you respond?",
        "Tell me about a time you took a calculated risk, similar to how Apple operates.",
        "How would you mentor a junior engineer joining your team at Apple?",
        "What is your strategy for learning a new proprietary technology used at Apple?",
        "How would you explain a complex technical concept to a non-technical manager at Apple?",
        "What do you think about Apple's impact on the global economy?",
        "How would you troubleshoot a memory leak in a core Apple application?",
        "Tell me about a time you exceeded expectations on a project, something Apple expects.",
        "How would you ensure your code is maintainable for future engineers at Apple?",
        "What is your opinion on Apple's current marketing strategy?"
    ],
    "Meta": [
        "Tell me about yourself.",
        "Why do you want to join Meta?",
        "How would you design a news feed algorithm?",
        "Describe a time you moved fast and broke things.",
        "How do you handle negative feedback on a product you built?",
        "How does Meta's business model differ from its competitors?",
        "Describe a time you used a product by Meta and found a bug.",
        "Why do you think Meta is a market leader?",
        "What is the biggest challenge Meta is facing today?",
        "If you were the CEO of Meta, what would you change?",
        "How would you improve Meta's core product?",
        "What excites you most about Meta's future roadmap?",
        "How do your personal values align with Meta's mission?",
        "Tell me about a time you had to adapt quickly, a skill highly valued at Meta.",
        "Describe a system you designed that could scale to Meta's level.",
        "What is your favorite feature of Meta's flagship product?",
        "How would you design a new feature for Meta?",
        "What do you know about Meta's recent acquisitions?",
        "How would you handle a production incident affecting millions of Meta's users?",
        "Tell me about a time you had to innovate, something Meta is known for.",
        "What makes Meta's company culture unique in your opinion?",
        "How do you stay updated with Meta's technological advancements?",
        "If hired at Meta, what would you aim to achieve in your first 90 days?",
        "How would you optimize an algorithm to run efficiently on Meta's infrastructure?",
        "Describe a time you demonstrated leadership principles valued at Meta.",
        "What is a recent news article you read about Meta, and what are your thoughts on it?",
        "How would you pitch Meta's services to a potential enterprise client?",
        "What do you think is Meta's biggest missed opportunity?",
        "If you could work on any team at Meta, which one would it be and why?",
        "How do you prioritize tasks when working on high-impact projects at Meta?",
        "What is your understanding of Meta's target demographic?",
        "How would you resolve a conflict with a colleague in a fast-paced environment like Meta?",
        "Tell me about a time you made a data-driven decision, a key practice at Meta.",
        "How would you ensure accessibility in products developed by Meta?",
        "What do you think of Meta's approach to open-source software?",
        "How would you reduce latency in Meta's primary application?",
        "Describe a time you received constructive feedback and how you applied it, as expected at Meta.",
        "What do you think is the next big industry trend Meta should focus on?",
        "How would you handle working with a globally distributed team at Meta?",
        "Tell me about a time you had to manage stakeholders with conflicting interests, common at Meta.",
        "What is your approach to testing and QA for large-scale systems like Meta's?",
        "How would you design a caching strategy for Meta's high-traffic web pages?",
        "What do you think about Meta's approach to user privacy and data security?",
        "If a major competitor of Meta launched a disruptive product, how would you respond?",
        "Tell me about a time you took a calculated risk, similar to how Meta operates.",
        "How would you mentor a junior engineer joining your team at Meta?",
        "What is your strategy for learning a new proprietary technology used at Meta?",
        "How would you explain a complex technical concept to a non-technical manager at Meta?",
        "What do you think about Meta's impact on the global economy?",
        "How would you troubleshoot a memory leak in a core Meta application?",
        "Tell me about a time you exceeded expectations on a project, something Meta expects.",
        "How would you ensure your code is maintainable for future engineers at Meta?",
        "What is your opinion on Meta's current marketing strategy?",
        "If you were given a budget to innovate at Meta, what project would you start?"
    ],
    "TCS": [
        "Tell me about yourself.",
        "Why do you want to join TCS?",
        "Are you willing to relocate for this role?",
        "Are you open to working in different shifts?",
        "What do you know about TCS's core services?",
        "How do you handle repetitive tasks?",
        "How does TCS's business model differ from its competitors?",
        "Describe a time you used a product by TCS and found a bug.",
        "Why do you think TCS is a market leader?",
        "What is the biggest challenge TCS is facing today?",
        "If you were the CEO of TCS, what would you change?",
        "How would you improve TCS's core product?",
        "What excites you most about TCS's future roadmap?",
        "How do your personal values align with TCS's mission?",
        "Tell me about a time you had to adapt quickly, a skill highly valued at TCS.",
        "Describe a system you designed that could scale to TCS's level.",
        "What is your favorite feature of TCS's flagship product?",
        "How would you design a new feature for TCS?",
        "What do you know about TCS's recent acquisitions?",
        "How would you handle a production incident affecting millions of TCS's users?",
        "Tell me about a time you had to innovate, something TCS is known for.",
        "What makes TCS's company culture unique in your opinion?",
        "How do you stay updated with TCS's technological advancements?",
        "If hired at TCS, what would you aim to achieve in your first 90 days?",
        "How would you optimize an algorithm to run efficiently on TCS's infrastructure?",
        "Describe a time you demonstrated leadership principles valued at TCS.",
        "What is a recent news article you read about TCS, and what are your thoughts on it?",
        "How would you pitch TCS's services to a potential enterprise client?",
        "What do you think is TCS's biggest missed opportunity?",
        "If you could work on any team at TCS, which one would it be and why?",
        "How do you prioritize tasks when working on high-impact projects at TCS?",
        "What is your understanding of TCS's target demographic?",
        "How would you resolve a conflict with a colleague in a fast-paced environment like TCS?",
        "Tell me about a time you made a data-driven decision, a key practice at TCS.",
        "How would you ensure accessibility in products developed by TCS?",
        "What do you think of TCS's approach to open-source software?",
        "How would you reduce latency in TCS's primary application?",
        "Describe a time you received constructive feedback and how you applied it, as expected at TCS.",
        "What do you think is the next big industry trend TCS should focus on?",
        "How would you handle working with a globally distributed team at TCS?",
        "Tell me about a time you had to manage stakeholders with conflicting interests, common at TCS.",
        "What is your approach to testing and QA for large-scale systems like TCS's?",
        "How would you design a caching strategy for TCS's high-traffic web pages?",
        "What do you think about TCS's approach to user privacy and data security?",
        "If a major competitor of TCS launched a disruptive product, how would you respond?",
        "Tell me about a time you took a calculated risk, similar to how TCS operates.",
        "How would you mentor a junior engineer joining your team at TCS?",
        "What is your strategy for learning a new proprietary technology used at TCS?",
        "How would you explain a complex technical concept to a non-technical manager at TCS?",
        "What do you think about TCS's impact on the global economy?",
        "How would you troubleshoot a memory leak in a core TCS application?",
        "Tell me about a time you exceeded expectations on a project, something TCS expects.",
        "How would you ensure your code is maintainable for future engineers at TCS?",
        "What is your opinion on TCS's current marketing strategy?",
        "If you were given a budget to innovate at TCS, what project would you start?",
        "How do you balance speed of delivery with code quality, a common dilemma at TCS?"
    ],
    "Infosys": [
        "Tell me about yourself.",
        "Why do you want to join Infosys?",
        "What do you know about Infosys's recent projects?",
        "How quickly can you learn a new technology?",
        "Describe a time you worked in a large team.",
        "How does Infosys's business model differ from its competitors?",
        "Describe a time you used a product by Infosys and found a bug.",
        "Why do you think Infosys is a market leader?",
        "What is the biggest challenge Infosys is facing today?",
        "If you were the CEO of Infosys, what would you change?",
        "How would you improve Infosys's core product?",
        "What excites you most about Infosys's future roadmap?",
        "How do your personal values align with Infosys's mission?",
        "Tell me about a time you had to adapt quickly, a skill highly valued at Infosys.",
        "Describe a system you designed that could scale to Infosys's level.",
        "What is your favorite feature of Infosys's flagship product?",
        "How would you design a new feature for Infosys?",
        "What do you know about Infosys's recent acquisitions?",
        "How would you handle a production incident affecting millions of Infosys's users?",
        "Tell me about a time you had to innovate, something Infosys is known for.",
        "What makes Infosys's company culture unique in your opinion?",
        "How do you stay updated with Infosys's technological advancements?",
        "If hired at Infosys, what would you aim to achieve in your first 90 days?",
        "How would you optimize an algorithm to run efficiently on Infosys's infrastructure?",
        "Describe a time you demonstrated leadership principles valued at Infosys.",
        "What is a recent news article you read about Infosys, and what are your thoughts on it?",
        "How would you pitch Infosys's services to a potential enterprise client?",
        "What do you think is Infosys's biggest missed opportunity?",
        "If you could work on any team at Infosys, which one would it be and why?",
        "How do you prioritize tasks when working on high-impact projects at Infosys?",
        "What is your understanding of Infosys's target demographic?",
        "How would you resolve a conflict with a colleague in a fast-paced environment like Infosys?",
        "Tell me about a time you made a data-driven decision, a key practice at Infosys.",
        "How would you ensure accessibility in products developed by Infosys?",
        "What do you think of Infosys's approach to open-source software?",
        "How would you reduce latency in Infosys's primary application?",
        "Describe a time you received constructive feedback and how you applied it, as expected at Infosys.",
        "What do you think is the next big industry trend Infosys should focus on?",
        "How would you handle working with a globally distributed team at Infosys?",
        "Tell me about a time you had to manage stakeholders with conflicting interests, common at Infosys.",
        "What is your approach to testing and QA for large-scale systems like Infosys's?",
        "How would you design a caching strategy for Infosys's high-traffic web pages?",
        "What do you think about Infosys's approach to user privacy and data security?",
        "If a major competitor of Infosys launched a disruptive product, how would you respond?",
        "Tell me about a time you took a calculated risk, similar to how Infosys operates.",
        "How would you mentor a junior engineer joining your team at Infosys?",
        "What is your strategy for learning a new proprietary technology used at Infosys?",
        "How would you explain a complex technical concept to a non-technical manager at Infosys?",
        "What do you think about Infosys's impact on the global economy?",
        "How would you troubleshoot a memory leak in a core Infosys application?",
        "Tell me about a time you exceeded expectations on a project, something Infosys expects.",
        "How would you ensure your code is maintainable for future engineers at Infosys?",
        "What is your opinion on Infosys's current marketing strategy?",
        "If you were given a budget to innovate at Infosys, what project would you start?",
        "How do you balance speed of delivery with code quality, a common dilemma at Infosys?",
        "What would you do if your project failed at Infosys?"
    ],
    "Wipro": [
        "Tell me about yourself.",
        "Why do you want to join Wipro?",
        "What is your understanding of Wipro's values?",
        "How do you handle tight deadlines?",
        "How does Wipro's business model differ from its competitors?",
        "Describe a time you used a product by Wipro and found a bug.",
        "Why do you think Wipro is a market leader?",
        "What is the biggest challenge Wipro is facing today?",
        "If you were the CEO of Wipro, what would you change?",
        "How would you improve Wipro's core product?",
        "What excites you most about Wipro's future roadmap?",
        "How do your personal values align with Wipro's mission?",
        "Tell me about a time you had to adapt quickly, a skill highly valued at Wipro.",
        "Describe a system you designed that could scale to Wipro's level.",
        "What is your favorite feature of Wipro's flagship product?",
        "How would you design a new feature for Wipro?",
        "What do you know about Wipro's recent acquisitions?",
        "How would you handle a production incident affecting millions of Wipro's users?",
        "Tell me about a time you had to innovate, something Wipro is known for.",
        "What makes Wipro's company culture unique in your opinion?",
        "How do you stay updated with Wipro's technological advancements?",
        "If hired at Wipro, what would you aim to achieve in your first 90 days?",
        "How would you optimize an algorithm to run efficiently on Wipro's infrastructure?",
        "Describe a time you demonstrated leadership principles valued at Wipro.",
        "What is a recent news article you read about Wipro, and what are your thoughts on it?",
        "How would you pitch Wipro's services to a potential enterprise client?",
        "What do you think is Wipro's biggest missed opportunity?",
        "If you could work on any team at Wipro, which one would it be and why?",
        "How do you prioritize tasks when working on high-impact projects at Wipro?",
        "What is your understanding of Wipro's target demographic?",
        "How would you resolve a conflict with a colleague in a fast-paced environment like Wipro?",
        "Tell me about a time you made a data-driven decision, a key practice at Wipro.",
        "How would you ensure accessibility in products developed by Wipro?",
        "What do you think of Wipro's approach to open-source software?",
        "How would you reduce latency in Wipro's primary application?",
        "Describe a time you received constructive feedback and how you applied it, as expected at Wipro.",
        "What do you think is the next big industry trend Wipro should focus on?",
        "How would you handle working with a globally distributed team at Wipro?",
        "Tell me about a time you had to manage stakeholders with conflicting interests, common at Wipro.",
        "What is your approach to testing and QA for large-scale systems like Wipro's?",
        "How would you design a caching strategy for Wipro's high-traffic web pages?",
        "What do you think about Wipro's approach to user privacy and data security?",
        "If a major competitor of Wipro launched a disruptive product, how would you respond?",
        "Tell me about a time you took a calculated risk, similar to how Wipro operates.",
        "How would you mentor a junior engineer joining your team at Wipro?",
        "What is your strategy for learning a new proprietary technology used at Wipro?",
        "How would you explain a complex technical concept to a non-technical manager at Wipro?",
        "What do you think about Wipro's impact on the global economy?",
        "How would you troubleshoot a memory leak in a core Wipro application?",
        "Tell me about a time you exceeded expectations on a project, something Wipro expects.",
        "How would you ensure your code is maintainable for future engineers at Wipro?",
        "What is your opinion on Wipro's current marketing strategy?",
        "If you were given a budget to innovate at Wipro, what project would you start?",
        "How do you balance speed of delivery with code quality, a common dilemma at Wipro?",
        "What would you do if your project failed at Wipro?",
        "How do you recover from setbacks at a company like Wipro?"
    ],
    "Accenture": [
        "Tell me about yourself.",
        "Why do you want to join Accenture?",
        "How do you adapt to different client environments?",
        "Describe a time you solved a problem for a client.",
        "How does Accenture's business model differ from its competitors?",
        "Describe a time you used a product by Accenture and found a bug.",
        "Why do you think Accenture is a market leader?",
        "What is the biggest challenge Accenture is facing today?",
        "If you were the CEO of Accenture, what would you change?",
        "How would you improve Accenture's core product?",
        "What excites you most about Accenture's future roadmap?",
        "How do your personal values align with Accenture's mission?",
        "Tell me about a time you had to adapt quickly, a skill highly valued at Accenture.",
        "Describe a system you designed that could scale to Accenture's level.",
        "What is your favorite feature of Accenture's flagship product?",
        "How would you design a new feature for Accenture?",
        "What do you know about Accenture's recent acquisitions?",
        "How would you handle a production incident affecting millions of Accenture's users?",
        "Tell me about a time you had to innovate, something Accenture is known for.",
        "What makes Accenture's company culture unique in your opinion?",
        "How do you stay updated with Accenture's technological advancements?",
        "If hired at Accenture, what would you aim to achieve in your first 90 days?",
        "How would you optimize an algorithm to run efficiently on Accenture's infrastructure?",
        "Describe a time you demonstrated leadership principles valued at Accenture.",
        "What is a recent news article you read about Accenture, and what are your thoughts on it?",
        "How would you pitch Accenture's services to a potential enterprise client?",
        "What do you think is Accenture's biggest missed opportunity?",
        "If you could work on any team at Accenture, which one would it be and why?",
        "How do you prioritize tasks when working on high-impact projects at Accenture?",
        "What is your understanding of Accenture's target demographic?",
        "How would you resolve a conflict with a colleague in a fast-paced environment like Accenture?",
        "Tell me about a time you made a data-driven decision, a key practice at Accenture.",
        "How would you ensure accessibility in products developed by Accenture?",
        "What do you think of Accenture's approach to open-source software?",
        "How would you reduce latency in Accenture's primary application?",
        "Describe a time you received constructive feedback and how you applied it, as expected at Accenture.",
        "What do you think is the next big industry trend Accenture should focus on?",
        "How would you handle working with a globally distributed team at Accenture?",
        "Tell me about a time you had to manage stakeholders with conflicting interests, common at Accenture.",
        "What is your approach to testing and QA for large-scale systems like Accenture's?",
        "How would you design a caching strategy for Accenture's high-traffic web pages?",
        "What do you think about Accenture's approach to user privacy and data security?",
        "If a major competitor of Accenture launched a disruptive product, how would you respond?",
        "Tell me about a time you took a calculated risk, similar to how Accenture operates.",
        "How would you mentor a junior engineer joining your team at Accenture?",
        "What is your strategy for learning a new proprietary technology used at Accenture?",
        "How would you explain a complex technical concept to a non-technical manager at Accenture?",
        "What do you think about Accenture's impact on the global economy?",
        "How would you troubleshoot a memory leak in a core Accenture application?",
        "Tell me about a time you exceeded expectations on a project, something Accenture expects.",
        "How would you ensure your code is maintainable for future engineers at Accenture?",
        "What is your opinion on Accenture's current marketing strategy?",
        "If you were given a budget to innovate at Accenture, what project would you start?",
        "How do you balance speed of delivery with code quality, a common dilemma at Accenture?",
        "What would you do if your project failed at Accenture?",
        "How do you recover from setbacks at a company like Accenture?",
        "How do you maintain a positive attitude at Accenture?"
    ]
}
