# Generated by Django 6.0.7 on 2026-08-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Admin', 'Admin')], default='Candidate', max_length=20),
        ),
    ]
