# Generated by Django 6.0.7 on 2026-08-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_questionbank_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='AI Interview Assistant', max_length=255)),
                ('theme_preference', models.CharField(default='dark', max_length=50)),
                ('language', models.CharField(default='en', max_length=50)),
                ('ai_model', models.CharField(default='gemini-1.5-pro', max_length=100)),
                ('ai_strictness', models.CharField(default='medium', max_length=50)),
                ('feedback_enabled', models.BooleanField(default=True)),
                ('default_duration_mins', models.IntegerField(default=30)),
                ('questions_per_interview', models.IntegerField(default=5)),
                ('passing_score', models.IntegerField(default=70)),
                ('email_alerts', models.BooleanField(default=True)),
                ('new_user_alerts', models.BooleanField(default=False)),
                ('open_registration', models.BooleanField(default=True)),
                ('default_role', models.CharField(default='Candidate', max_length=20)),
                ('allow_resume_uploads', models.BooleanField(default=True)),
                ('ai_resume_analysis', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
