# Generated by Django 6.0.7 on 2026-08-10 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_systemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterviewSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(default='Technical Interview', max_length=100)),
                ('difficulty_level', models.CharField(default='Medium', max_length=50)),
                ('interview_duration', models.CharField(default='30 Minutes', max_length=50)),
                ('number_of_questions', models.CharField(default='10 Questions', max_length=50)),
                ('language', models.CharField(default='English', max_length=50)),
                ('enable_voice', models.BooleanField(default=True)),
                ('show_hints', models.BooleanField(default=True)),
                ('record_interview', models.BooleanField(default=False)),
                ('feedback_performance', models.CharField(default='Detailed Feedback', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
